#!/usr/bin/env bash
#----------------------------------------------------------------------
# Script    : config
# Descrição : Script para configuração rápida do git
# Versão    : 0.1
# Autor     : Fabio Junior Ribeiro <rib3iro@live.com>
# Data      : 27/05/2020
# Licença   : GNU/GPL v3.0
#----------------------------------------------------------------------
# Uso       :
#----------------------------------------------------------------------

# variaveis
blue='\e[34;1m'
green='\e[32;1m'
red='\e[31;1m'
end='\e[m'
seta='\e[32;1m==>\e[m'
texto="Commit básico para não ficar digitando o tempo todo!"

echo -en "$seta ${blue}Deseja configurar o git${end} ${red}[s/n]${end}${blue}? ${end}"
read resposta
clear

if [[ "$resposta" == @(S|s) ]]; then
    echo -e "$seta ${blue}Iniciando a configuração do git.${end}"
    sleep 2s
    clear

    echo -e "$seta ${blue}Configurando nome de usuário.${end}"
    git config --global user.name Fabio Ribeiro
    sleep 2s
    clear

    echo -e "$seta ${blue}Configurando email.${end}"
    git config --global user.email rib3iro@live.com
    sleep 2s
    clear
    echo -e "$seta ${blue}Configurando editor padrão.${end}"
    git config --global core.editor vim
    sleep 2s
    clear

    echo -e "$seta ${blue}Configurando o vimdiff.${end}"
    git config --global core.editor vimdiff
    sleep 2s
    clear

    echo -e "$seta ${blue}Listando a configuração do git.${end}"
    git config --list
    sleep 2s
    clear
else
    echo -e "$seta ${blue}Adicionando arquivos.${end}"
    git add *
    sleep 2s
    clear

    echo -e "$seta ${blue}Verificando o status.${end}"
    git status
    sleep 2s
    clear

    #echo -en "$seta ${blue}Digite o texto do commit:${end} "
    echo -e "$seta ${red}Escrevendo o texto chato do commit${end}"
    git commit -m "$texto"
    sleep 2s
    clear

    echo -e "$seta ${blue}Fazendo o push.${end}"
    git push origin master
    sleep 2s
    clear
fi
